### ISSUE TITLE
Error: "extra_build_options_"

### ISSUE THREAD

**Issue by j5207** [intel/ros_opencl_caffe#3] opened 2018-02-07 02:56 UTC
Hi all:
when I do `catkin_make` in my catkin workspace, I found out that there always be a extra_build option error, like this:
![11](https://user-images.githubusercontent.com/33009871/35896085-7b468180-0b88-11e8-85ee-90c2e562e902.png)
It would be much appreciate if anyone could help me out

Thanks,
Ji

**Comment by xhuan28** [comment] 2018-02-26 03:45
It is an issue caused by the [latest commit](https://github.com/01org/caffe/commit/3eb1dfdc87f24a19c2c7aa66ffcac6ca27a30d1f) of clCaffe.  I have reported an [issue](https://github.com/01org/caffe/issues/109) to them. 
At this moment, I think the quickest way to solve this problem is to abandon the latest commit and use this commit(https://github.com/01org/caffe/commit/2a73199d862b63b41497098fa926f0e35ab41fc2).
Hope it is help for you.

**Comment by j5207** [comment] 2018-02-26 18:58
Thanks for your reply. However, after pulling the corrected version of clcaffe, it seem still contain errors:
`CMakeFiles/opencl_caffe_srv.dir/src/detector_gpu.cpp.o: In function `int opencl_caffe::DetectorGpu::initNetwork<half_float::half>(std::shared_ptr<caffe::Net<half_float::half> >&, std::vector<half_float::half*, std::allocator<half_float::half*> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
detector_gpu.cpp:(.text._ZN12opencl_caffe11DetectorGpu11initNetworkIN10half_float4halfEEEiRSt10shared_ptrIN5caffe3NetIT_EEERSt6vectorIPS7_SaISC_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESN_SN_[_ZN12opencl_caffe11DetectorGpu11initNetworkIN10half_float4halfEEEiRSt10shared_ptrIN5caffe3NetIT_EEERSt6vectorIPS7_SaISC_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESN_SN_]+0x7e): undefined reference to `caffe::Net<half_float::half>::Net(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, caffe::Phase, caffe::device*, int, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const*)'
detector_gpu.cpp:(.text._ZN12opencl_caffe11DetectorGpu11initNetworkIN10half_float4halfEEEiRSt10shared_ptrIN5caffe3NetIT_EEERSt6vectorIPS7_SaISC_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESN_SN_[_ZN12opencl_caffe11DetectorGpu11initNetworkIN10half_float4halfEEEiRSt10shared_ptrIN5caffe3NetIT_EEERSt6vectorIPS7_SaISC_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESN_SN_]+0xc7): undefined reference to `caffe::Net<half_float::half>::CopyTrainedLayersFrom(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
detector_gpu.cpp:(.text._ZN12opencl_caffe11DetectorGpu11initNetworkIN10half_float4halfEEEiRSt10shared_ptrIN5caffe3NetIT_EEERSt6vectorIPS7_SaISC_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESN_SN_[_ZN12opencl_caffe11DetectorGpu11initNetworkIN10half_float4halfEEEiRSt10shared_ptrIN5caffe3NetIT_EEERSt6vectorIPS7_SaISC_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESN_SN_]+0x1a3): undefined reference to `caffe::Blob<half_float::half>::Reshape(int, int, int, int)'
detector_gpu.cpp:(.text._ZN12opencl_caffe11DetectorGpu11initNetworkIN10half_float4halfEEEiRSt10shared_ptrIN5caffe3NetIT_EEERSt6vectorIPS7_SaISC_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESN_SN_[_ZN12opencl_caffe11DetectorGpu11initNetworkIN10half_float4halfEEEiRSt10shared_ptrIN5caffe3NetIT_EEERSt6vectorIPS7_SaISC_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESN_SN_]+0x1ba): undefined reference to `caffe::Net<half_float::half>::Reshape()'
detector_gpu.cpp:(.text._ZN12opencl_caffe11DetectorGpu11initNetworkIN10half_float4halfEEEiRSt10shared_ptrIN5caffe3NetIT_EEERSt6vectorIPS7_SaISC_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESN_SN_[_ZN12opencl_caffe11DetectorGpu11initNetworkIN10half_float4halfEEEiRSt10shared_ptrIN5caffe3NetIT_EEERSt6vectorIPS7_SaISC_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESN_SN_]+0x1c9): undefined reference to `caffe::Blob<half_float::half>::mutable_cpu_data()'
detector_gpu.cpp:(.text._ZN12opencl_caffe11DetectorGpu11initNetworkIN10half_float4halfEEEiRSt10shared_ptrIN5caffe3NetIT_EEERSt6vectorIPS7_SaISC_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESN_SN_[_ZN12opencl_caffe11DetectorGpu11initNetworkIN10half_float4halfEEEiRSt10shared_ptrIN5caffe3NetIT_EEERSt6vectorIPS7_SaISC_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESN_SN_]+0x3a5): undefined reference to `caffe::Net<half_float::half>::Forward(half_float::half*)'
CMakeFiles/opencl_caffe_srv.dir/src/detector_gpu.cpp.o: In function `int opencl_caffe::DetectorGpu::inference<half_float::half>(std::shared_ptr<caffe::Net<half_float::half> >&, std::vector<half_float::half*, std::allocator<half_float::half*> >&, boost::shared_ptr<sensor_msgs::Image_<std::allocator<void> > >, object_msgs::ObjectsInBoxes_<std::allocator<void> >&)':
detector_gpu.cpp:(.text._ZN12opencl_caffe11DetectorGpu9inferenceIN10half_float4halfEEEiRSt10shared_ptrIN5caffe3NetIT_EEERSt6vectorIPS7_SaISC_EEN5boost10shared_ptrIN11sensor_msgs6Image_ISaIvEEEEERN11object_msgs15ObjectsInBoxes_ISK_EE[_ZN12opencl_caffe11DetectorGpu9inferenceIN10half_float4halfEEEiRSt10shared_ptrIN5caffe3NetIT_EEERSt6vectorIPS7_SaISC_EEN5boost10shared_ptrIN11sensor_msgs6Image_ISaIvEEEEERN11object_msgs15ObjectsInBoxes_ISK_EE]+0x1df): undefined reference to `caffe::Net<half_float::half>::Forward(half_float::half*)'
detector_gpu.cpp:(.text._ZN12opencl_caffe11DetectorGpu9inferenceIN10half_float4halfEEEiRSt10shared_ptrIN5caffe3NetIT_EEERSt6vectorIPS7_SaISC_EEN5boost10shared_ptrIN11sensor_msgs6Image_ISaIvEEEEERN11object_msgs15ObjectsInBoxes_ISK_EE[_ZN12opencl_caffe11DetectorGpu9inferenceIN10half_float4halfEEEiRSt10shared_ptrIN5caffe3NetIT_EEERSt6vectorIPS7_SaISC_EEN5boost10shared_ptrIN11sensor_msgs6Image_ISaIvEEEEERN11object_msgs15ObjectsInBoxes_ISK_EE]+0x248): undefined reference to `caffe::Blob<half_float::half>::cpu_data() const'
collect2: error: ld returned 1 exit status
ros_opencl_caffe/opencl_caffe/CMakeFiles/opencl_caffe_srv.dir/build.make:200: recipe for target '/home/intuitivecompting/catkin_ws/devel/lib/opencl_caffe/opencl_caffe_srv' failed
make[2]: *** [/home/intuitivecompting/catkin_ws/devel/lib/opencl_caffe/opencl_caffe_srv] Error 1
CMakeFiles/Makefile2:4650: recipe for target 'ros_opencl_caffe/opencl_caffe/CMakeFiles/opencl_caffe_srv.dir/all' failed
make[1]: *** [ros_opencl_caffe/opencl_caffe/CMakeFiles/opencl_caffe_srv.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/home/intuitivecompting/catkin_ws/devel/lib/libopencl_caffe_nodelet.so: undefined reference to `caffe::Net<half_float::half>::Reshape()'
/home/intuitivecompting/catkin_ws/devel/lib/libopencl_caffe_nodelet.so: undefined reference to `caffe::Net<half_float::half>::Net(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, caffe::Phase, caffe::device*, int, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const*)'
/home/intuitivecompting/catkin_ws/devel/lib/libopencl_caffe_nodelet.so: undefined reference to `caffe::Blob<half_float::half>::mutable_cpu_data()'
/home/intuitivecompting/catkin_ws/devel/lib/libopencl_caffe_nodelet.so: undefined reference to `caffe::Net<half_float::half>::CopyTrainedLayersFrom(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
/home/intuitivecompting/catkin_ws/devel/lib/libopencl_caffe_nodelet.so: undefined reference to `caffe::Blob<half_float::half>::Reshape(int, int, int, int)'
/home/intuitivecompting/catkin_ws/devel/lib/libopencl_caffe_nodelet.so: undefined reference to `caffe::Net<half_float::half>::Forward(half_float::half*)'
/home/intuitivecompting/catkin_ws/devel/lib/libopencl_caffe_nodelet.so: undefined reference to `caffe::Blob<half_float::half>::cpu_data() const'
collect2: error: ld returned 1 exit status
ros_opencl_caffe/opencl_caffe/CMakeFiles/unittest_detector.dir/build.make:211: recipe for target '/home/intuitivecompting/catkin_ws/devel/lib/opencl_caffe/unittest_detector' failed
make[2]: *** [/home/intuitivecompting/catkin_ws/devel/lib/opencl_caffe/unittest_detector] Error 1
CMakeFiles/Makefile2:3467: recipe for target 'ros_opencl_caffe/opencl_caffe/CMakeFiles/unittest_detector.dir/all' failed
make[1]: *** [ros_opencl_caffe/opencl_caffe/CMakeFiles/unittest_detector.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j8 -l8" failed
`

**Comment by xhuan28** [comment] 2018-03-02 06:59
I can't reproduce the issue you met on my side. On the other hand, the previous issue(https://github.com/01org/caffe/issues/109) has been fixed in the latest commit(https://github.com/01org/caffe/commit/2df19aecd42b485240683f84842bbea5d80b5912) of clCaffe. Could you try it again?

**Comment by j5207** [comment] 2018-03-02 19:02
Thanks for your response.
yeah I clone the latest clcaffe and still got stuck.
May I ask that do you implement this on Nvidia platform? Also, do you turn on the ISAAC during clcaffe compiling?

Thanks!

**Comment by xhuan28** [comment] 2018-03-03 08:05
The target platform of this project is x86 platform with integrated GPU, such as skylake, but not Nvidia platform.

**Closed as completed** 2018-03-07 01:07 UTC
