### ISSUE TITLE
Error running realsense_viewer.launch

### ISSUE THREAD

**Issue by fiorano10** [intel/ros_opencl_caffe#10] opened 2018-05-08 02:33 UTC
I installed clCaffe, but to run the AlexNet example I had to choose gpu1, instead of gpu 0. Now when I run realsense_viewer.launch, I keep getting this error:

`I0507 22:30:44.239322 14775 net.cpp:281] Memory required for data: 86785584
Device : Intel(R) HD Graphics 6000 BroadWell U-Processor GT3Build Status = -2
Build Log = stringInput.cl:5558:1: warning: implicit declaration of function 'intel_sub_group_block_read8' is invalid in C99
stringInput.cl:5543:39: note: expanded from macro 'GEMM_NN'
stringInput.cl:5405:50: note: expanded from macro 'SUBGROUP_BLOCK_READ8'
stringInput.cl:5558:1: error: call to 'as_float8' is ambiguous
stringInput.cl:5543:28: note: expanded from macro 'GEMM_NN'
/usr/lib/x86_64-linux-gnu/beignet//include/ocl_as.h:492:21: note: candidate function
/usr/lib/x86_64-linux-gnu/beignet//include/ocl_as.h:502:21: note: candidate function
/usr/lib/x86_64-linux-gnu/beignet//include/ocl_as.h:512:21: note: candidate function
/usr/lib/x86_64-linux-gnu/beignet//include/ocl_as.h:522:21: note: candidate function
/usr/lib/x86_64-linux-gnu/beignet//include/ocl_as.h:533:21: note: candidate function
/usr/lib/x86_64-linux-gnu/beignet//include/ocl_as.h:544:21: note: candidate function
/usr/lib/x86_64-linux-gnu/beignet//include/ocl_as.h:555:21: note: candidate function
/usr/lib/x86_64-linux-gnu/beignet//
[FATAL] [1525746644.959104781]: Failed to load nodelet '/opencl_caffe_nodelet` of type `opencl_caffe/opencl_caffe_nodelet` to manager `opencl_caffe_manager'
[opencl_caffe_nodelet-3] process has died [pid 14782, exit code 255, cmd /opt/ros/kinetic/lib/nodelet/nodelet load opencl_caffe/opencl_caffe_nodelet opencl_caffe_manager /usb_cam/image_raw:=/camera/infra2/image_rect_raw_mono8 inference:=/opencl_caffe/inference __name:=opencl_caffe_nodelet __log:=/home/burro/.ros/log/ce6453ee-5267-11e8-ae8c-00e84c68eb85/opencl_caffe_nodelet-3.log].
log file: /home/burro/.ros/log/ce6453ee-5267-11e8-ae8c-00e84c68eb85/opencl_caffe_nodelet-3*.log`

**Comment by chaoli2** [comment] 2018-07-05 08:58
@fiorano10 
Sorry for the late response. Can you give more details about how to reproduce this issue, including:
1. which source files and configuration files are changed before launching ROS nodes?
2. which commands you use?
Thanks.

**Comment by fiorano10** [comment] 2018-07-09 18:26
@chaoli2 It seems the issue is caused if you have an install of beignet, removing it fixed the issue.

**Comment by chaoli2** [comment] 2018-07-10 03:07
@fiorano10 
Thanks very much for your update.  Close this thread since problem solved.

**Closed as completed by chaoli2** 2018-07-10 03:07 UTC
Labels: bug
