### ISSUE TITLE
No member object vector & No member image

### ISSUE THREAD

**Issue by fiorano10** [intel/ros_opencl_caffe#6] opened 2018-03-28 20:59 UTC
When I do catkin_make for ros_opencl_caffe & object_msgs, I get this error:

`/home/agr/catkin_practice_ws/src/ros_opencl_caffe/opencl_caffe/tests/unittest_srv.cpp: In member function ‘virtual void UnitTestSrv_testSrv_Test::TestBody()’:
/home/agr/catkin_practice_ws/src/ros_opencl_caffe/opencl_caffe/tests/unittest_srv.cpp:65:49: error: ‘object_msgs::DetectObject::Request {aka struct object_msgs::DetectObjectRequest_<std::allocator<void> >}’ has no member named ‘image’
   convertFrameToMessage(&image, 0, &inf.request.image);
                                                 ^
In file included from /usr/include/gtest/gtest.h:1929:0,
                 from /home/agr/catkin_practice_ws/src/ros_opencl_caffe/opencl_caffe/tests/unittest_srv.cpp:21:
/home/agr/catkin_practice_ws/src/ros_opencl_caffe/opencl_caffe/tests/unittest_srv.cpp:68:34: error: ‘object_msgs::DetectObjectResponse_<std::allocator<void> >::_objects_type {aka class std::vector<object_msgs::ObjectsInBoxes_<std::allocator<void> >, std::allocator<object_msgs::ObjectsInBoxes_<std::allocator<void> > > >}’ has no member named ‘objects_vector’
   ASSERT_GE(inf.response.objects.objects_vector.size(), 1);
                                  ^
Scanning dependencies of target opencl_caffe_viewer
[ 64%] Building CXX object ros_opencl_caffe/opencl_caffe/CMakeFiles/opencl_caffe_nodelet.dir/src/nodelet.cpp.o
[ 65%] Building CXX object ros_opencl_caffe/opencl_caffe/CMakeFiles/opencl_caffe_srv.dir/src/srv.cpp.o
[ 65%] Building CXX object ros_opencl_caffe/opencl_caffe_viewer/CMakeFiles/opencl_caffe_viewer.dir/src/opencl_caffe_viewer.cpp.o
ros_opencl_caffe/opencl_caffe/CMakeFiles/unittest_srv.dir/build.make:62: recipe for target 'ros_opencl_caffe/opencl_caffe/CMakeFiles/unittest_srv.dir/tests/unittest_srv.cpp.o' failed
make[2]: *** [ros_opencl_caffe/opencl_caffe/CMakeFiles/unittest_srv.dir/tests/unittest_srv.cpp.o] Error 1
CMakeFiles/Makefile2:5107: recipe for target 'ros_opencl_caffe/opencl_caffe/CMakeFiles/unittest_srv.dir/all' failed
make[1]: *** [ros_opencl_caffe/opencl_caffe/CMakeFiles/unittest_srv.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 65%] Building CXX object ros_opencl_caffe/opencl_caffe/CMakeFiles/opencl_caffe_srv.dir/src/detector_gpu.cpp.o
/home/agr/catkin_practice_ws/src/ros_opencl_caffe/opencl_caffe/src/srv.cpp: In member function ‘bool opencl_caffe::Srv::handleService(object_msgs::DetectObject::Request&, object_msgs::DetectObject::Response&)’:
/home/agr/catkin_practice_ws/src/ros_opencl_caffe/opencl_caffe/src/srv.cpp:46:76: error: ‘object_msgs::DetectObject::Request {aka struct object_msgs::DetectObjectRequest_<std::allocator<void> >}’ has no member named ‘image’
   sensor_msgs::ImagePtr image = boost::make_shared<sensor_msgs::Image>(req.image);
                                                                            ^
/home/agr/catkin_practice_ws/src/ros_opencl_caffe/opencl_caffe/src/srv.cpp:47:51: error: no matching function for call to ‘opencl_caffe::Detector::runInference(sensor_msgs::ImagePtr&, object_msgs::DetectObjectResponse_<std::allocator<void> >::_objects_type&)’
   if (!detector_->runInference(image, resp.objects))`

**Comment by xhuan28** [comment] 2018-03-29 07:24
This issue is caused by the definition change of [object_msgs](https://github.com/intel/object_msgs). I am working on fixing this issue. This issue should be fixed in a day or two. Stay tunned.

**Comment by xhuan28** [comment] 2018-03-29 07:51
Please update code to the latest commit(https://github.com/intel/ros_opencl_caffe/commit/ad4724b40712a9971621d1d7821007c97d2a3301). This issue has been fixed.

**Comment by fiorano10** [comment] 2018-03-29 17:17
Now I'm getting this:

`CMakeFiles/opencl_caffe_viewer.dir/src/opencl_caffe_viewer.cpp.o: In function `cbTimeSync(boost::shared_ptr<sensor_msgs::Image_<std::allocator<void> > const> const&, boost::shared_ptr<object_msgs::ObjectsInBoxes_<std::allocator<void> > const> const&)':
opencl_caffe_viewer.cpp:(.text+0x3ad): undefined reference to `cv::putText(cv::Mat&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cv::Point_<int>, int, double, cv::Scalar_<double>, int, int, bool)'
opencl_caffe_viewer.cpp:(.text+0x7ce): undefined reference to `cv::rectangle(cv::Mat&, cv::Point_<int>, cv::Point_<int>, cv::Scalar_<double> const&, int, int, int)'
opencl_caffe_viewer.cpp:(.text+0x8bf): undefined reference to `cv::_InputArray::_InputArray(cv::Mat const&)'
opencl_caffe_viewer.cpp:(.text+0x8ee): undefined reference to `cv::imshow(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cv::_InputArray const&)'
collect2: error: ld returned 1 exit status
ros_opencl_caffe/opencl_caffe_viewer/CMakeFiles/opencl_caffe_viewer.dir/build.make:169: recipe for target '/home/agr/catkin_practice_ws/devel/lib/opencl_caffe_viewer/opencl_caffe_viewer' failed
make[2]: *** [/home/agr/catkin_practice_ws/devel/lib/opencl_caffe_viewer/opencl_caffe_viewer] Error 1
CMakeFiles/Makefile2:6641: recipe for target 'ros_opencl_caffe/opencl_caffe_viewer/CMakeFiles/opencl_caffe_viewer.dir/all' failed
make[1]: *** [ros_opencl_caffe/opencl_caffe_viewer/CMakeFiles/opencl_caffe_viewer.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 58%] Built target robot_localization_generate_messages_eus
[ 58%] Built target robot_localization_generate_messages_cpp
/usr/bin/ld: CMakeFiles/opencl_caffe_srv.dir/src/srv.cpp.o: undefined reference to symbol '_ZN2cv6imreadERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEi'
/home/agr/catkin_practice_ws/devel/lib/libopencv_highgui.so.2.4: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
ros_opencl_caffe/opencl_caffe/CMakeFiles/opencl_caffe_srv.dir/build.make:200: recipe for target '/home/agr/catkin_practice_ws/devel/lib/opencl_caffe/opencl_caffe_srv' failed
make[2]: *** [/home/agr/catkin_practice_ws/devel/lib/opencl_caffe/opencl_caffe_srv] Error 1
CMakeFiles/Makefile2:5281: recipe for target 'ros_opencl_caffe/opencl_caffe/CMakeFiles/opencl_caffe_srv.dir/all' failed`

**Comment by xhuan28** [comment] 2018-03-30 05:23
It seems like something wrong with the opencv. Please double check the installation of opencv.

opencl_caffe_viewer.cpp:(.text+0x3ad): undefined reference to cv::putText(cv::Mat&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cv::Point_<int>, int, double, cv::Scalar_<double>, int, int, bool)' opencl_caffe_viewer.cpp:(.text+0x7ce): undefined reference tocv::rectangle(cv::Mat&, cv::Point_, cv::Point_, cv::Scalar_ const&, int, int, int)'

**Comment by fiorano10** [comment] 2018-03-30 16:20
I fixed the errors by changing the _find_package_(OpenCV) to (OpenCV 3.3). Thanks!

**Closed as completed** 2018-04-04 19:22 UTC
